name: Weekly Python Scrapper

on:
  schedule:
    # Runs at 00:00 every Sunday
    - cron: '06 13 * * *'

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.6' # Replace '3.x' with the version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt # Replace with your actual requirements file

      - name: Run the script 1
        run: python python/scrapper.py # Replace with the path to your script

      - name: Run the script 2
        run: python python/aggregator.py # Replace with the path to your script

      - name: Run the script 3
        run: python python/crop.py # Replace with the path to your script

      - name: Run the script 4
        run: python python/optimise.py # Replace with the path to your script

      - name: Check for changes
        id: git-check
        run: |
          git add -A
          git diff --staged --exit-code || echo "::set-output name=changes_detected::true"

      - name: Commit and push if changes
        run: |
          git config --global user.name 'NielsMinssen'
          git config --global user.email 'niels.minssen@gmail.com'
          git add -A
          git commit -m 'Automated script update' --allow-empty
          # Use the PAT stored in your repository secrets for the HTTPS authentication
          git push --set-upstream https://${{ secrets.GRANDSLAMS }}@github.com/NielsMinssen/GrandSlamChampions.git HEAD:main
      
